export const PORTFOLIO = [
  {
    title: "Como si fuera una isoca",
    year: "2024",
    subtitle: "design, html, css",
    url: "https://como-si-fuera-una-isoca.netlify.app/",
    code: "",
    image: "como-si-fuera-una-isoca.png",
  },
  {
    title: "Chef IA",
    year: "2024",
    subtitle: "design, astro, javascript, python, ia",
    url: "https://github.com/NicMotta/chef-ia",
    code: "https://github.com/NicMotta/chef-ia",
    image: "chef-ia.gif",
  },
  {
    title: "Laboratorio de Indicadores Culturales",
    year: "2022 / 2024",
    subtitle: "design, astro, javascript, data",
    url: "https://indicadores-culturales.vercel.app/",
    code: "",
    image: "indicadores-culturales.png",
  },
  {
    title:
      "Cátedra De Piero - Universidad Nacional de las Artes - Artes Visuales",
    year: "2023",
    subtitle: "design, astro, javascript",
    url: "https://catedra-de-piero.vercel.app/",
    code: "",
    image: "catedra-de-piero.png",
  },
  {
    title: "Respir0 Namiki 2.0",
    year: "2022 / 2023",
    subtitle: "design, javascript",
    url: "https://muru7-8.github.io/respiro-namiki/",
    code: "",
    image: "respiro-namiki-2.png",
  },
  {
    title: "App-Bike",
    year: "2022",
    subtitle: "design, react",
    url: "https://app-bike-build.netlify.app/",
    code: "https://github.com/NicMotta/app-bike-desarrollo",
    image: "app-bike.png",
  },
  {
    title: "App-Clima",
    year: "2022",
    subtitle: "react",
    url: "https://nicmotta.github.io/clima-app/",
    code: "https://github.com/NicMotta/clima-app-react-desarroll",
    image: "clima-app.png",
  },
  {
    title: "Visual data",
    year: "2022",
    subtitle: "javascript",
    url: "https://nicmotta.github.io/VisualizadorJavascript/",
    code: "https://github.com/NicMotta/VisualizadorJavascript",
    image: "visualizadorcsv.png",
  },
  {
    title: "MURU 7.8",
    year: "2021",
    subtitle: "html, css, javascript",
    url: "https://muru7-8.github.io/",
    code: "https://github.com/muru7-8/muru7-8.github.io",
    image: "muru.png",
  },
  {
    title: "Respir0 Namiki",
    year: "2021",
    subtitle: "design, javascript",
    url: "https://muru7-8.github.io/respir0-namiki/",
    code: "https://github.com/muru7-8/respir0-namiki",
    image: "respir0-namiki.png",
  },
  {
    title:
      "Derivas Virtuales - Facultad de Arquitectura, Diseño y Urbanismo - Cátedra La Ferla",
    year: "2021",
    subtitle: "design, html, css, javascript",
    url: "https://derivasvirtuales.com.ar/",
    code: "",
    image: "derivas-virtuales.png",
  },
  {
    title: "Comic interactivo - Matar a los tiranxs",
    year: "2021",
    subtitle: "design, html, css, javascript",
    url: "https://mataralostiranos.github.io/",
    code: "",
    image: "mataralostiranxs.png",
  },
  {
    title: "Namiki Universo Digital - MURU 7.8",
    year: "2020",
    subtitle: "design, javascript",
    url: "https://namiki-universo-digital.netlify.app/",
    code: "",
    image: "namiki-digital.png",
  },
  {
    title:
      "Grup3 - Maestría en Técnologías y Esteticas de las Artes Electrónicas",
    year: "2020",
    subtitle: "javascript",
    url: "https://nicmotta.github.io/grup3_sonido/",
    code: "",
    image: "grup3.png",
  },
  {
    title: "Magali Mc Grath - Portfolio",
    year: "2019",
    subtitle: "html, css, javascript",
    url: "https://tiempoheredado.github.io/",
    code: "",
    image: "tiempoheredado.png",
  },
];
